// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3tnvYWzLjEKTA5n1OkuAdyno-JpZ9biw',
    appId: '1:295530556200:web:adf34415def207ed3fbe1d',
    messagingSenderId: '295530556200',
    projectId: 'hijeshi-13b27',
    authDomain: 'hijeshi-13b27.firebaseapp.com',
    storageBucket: 'hijeshi-13b27.firebasestorage.app',
    measurementId: 'G-KHF3QB0L17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRl2_D_1nj-d2X9DeXuJ8VOf1XXCsU0mo',
    appId: '1:295530556200:android:ede86e80ad8233323fbe1d',
    messagingSenderId: '295530556200',
    projectId: 'hijeshi-13b27',
    storageBucket: 'hijeshi-13b27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2G-ayY8NMh_PWZjeKlMHDxVBKcL3wxT8',
    appId: '1:295530556200:ios:17af77cb779c70a93fbe1d',
    messagingSenderId: '295530556200',
    projectId: 'hijeshi-13b27',
    storageBucket: 'hijeshi-13b27.firebasestorage.app',
    iosBundleId: 'com.hijeshi.hijeshi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2G-ayY8NMh_PWZjeKlMHDxVBKcL3wxT8',
    appId: '1:295530556200:ios:17af77cb779c70a93fbe1d',
    messagingSenderId: '295530556200',
    projectId: 'hijeshi-13b27',
    storageBucket: 'hijeshi-13b27.firebasestorage.app',
    iosBundleId: 'com.hijeshi.hijeshi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3tnvYWzLjEKTA5n1OkuAdyno-JpZ9biw',
    appId: '1:295530556200:web:d62113ad0f4ee9123fbe1d',
    messagingSenderId: '295530556200',
    projectId: 'hijeshi-13b27',
    authDomain: 'hijeshi-13b27.firebaseapp.com',
    storageBucket: 'hijeshi-13b27.firebasestorage.app',
    measurementId: 'G-GFQH5CMP1Y',
  );
}
